/* The only I/O in the app: static JSON generated by `src.export.bundle`.
   No API calls, no credentials, nothing to leak into the bundle. */

import { useEffect, useRef, useState } from "react";

const BASE = import.meta.env.BASE_URL;
const cache = new Map();

function load(path) {
  if (!cache.has(path)) {
    cache.set(
      path,
      fetch(`${BASE}data/${path}`).then((r) => {
        if (!r.ok) throw new Error(`${path}: ${r.status}`);
        return r.json();
      }),
    );
  }
  return cache.get(path);
}

export function useJson(path) {
  const [state, setState] = useState({ data: null, error: null });

  useEffect(() => {
    let live = true;
    setState({ data: null, error: null });
    load(path)
      .then((data) => live && setState({ data, error: null }))
      .catch((error) => live && setState({ data: null, error }));
    return () => {
      live = false;
    };
  }, [path]);

  return state;
}

/** Current hash route: `#/` or `#/match/<id>`. */
export function useRoute() {
  const read = () => window.location.hash.replace(/^#\/?/, "");
  const [route, setRoute] = useState(read);

  useEffect(() => {
    const onChange = () => {
      setRoute(read());
      window.scrollTo(0, 0);
    };
    window.addEventListener("hashchange", onChange);
    return () => window.removeEventListener("hashchange", onChange);
  }, []);

  return route;
}

/** Container width, so charts size to the viewport instead of guessing. */
export function useWidth(fallback = 720) {
  const ref = useRef(null);
  const [width, setWidth] = useState(fallback);

  useEffect(() => {
    const node = ref.current;
    if (!node) return;
    const ro = new ResizeObserver(([entry]) => {
      const w = entry.contentRect.width;
      if (w > 0) setWidth(w);
    });
    ro.observe(node);
    return () => ro.disconnect();
  }, []);

  return [ref, width];
}

export const fmt = (n) =>
  n === null || n === undefined ? "—" : Math.round(n).toLocaleString("en-US");
