/* The only I/O in the app: static JSON generated by `src.export.bundle`.
   No API calls, no credentials, nothing to leak into the bundle. */

import { useEffect, useRef, useState } from "react";

const BASE = import.meta.env.BASE_URL;
const cache = new Map();

function load(path) {
  if (!cache.has(path)) {
    cache.set(
      path,
      fetch(`${BASE}data/${path}`).then((r) => {
        if (!r.ok) throw new Error(`${path}: ${r.status}`);
        return r.json();
      }),
    );
  }
  return cache.get(path);
}

export function useJson(path) {
  const [state, setState] = useState({ data: null, error: null });

  useEffect(() => {
    let live = true;
    setState({ data: null, error: null });
    load(path)
      .then((data) => live && setState({ data, error: null }))
      .catch((error) => live && setState({ data: null, error }));
    return () => {
      live = false;
    };
  }, [path]);

  return state;
}

/** Current hash route: `#/` or `#/match/<id>`.
 *
 *  Only a hash starting with `#/` is a route. Bare fragments like `#matches`
 *  are in-page anchors for the header nav and must resolve to the home route,
 *  not to a view of their own -- otherwise every anchor click would be read as
 *  a navigation and reset the scroll position the browser just set. */
const readRoute = () => {
  const hash = typeof window === "undefined" ? "" : window.location.hash;
  return hash.startsWith("#/") ? hash.slice(2) : "";
};

export function useRoute() {
  const [route, setRoute] = useState(readRoute);

  useEffect(() => {
    const onChange = () => {
      setRoute((prev) => {
        const next = readRoute();
        // Scroll resets on a real view change only. An anchor click leaves the
        // route untouched, and scrolling to the top would undo the jump.
        if (next !== prev) window.scrollTo(0, 0);
        return next;
      });
    };
    window.addEventListener("hashchange", onChange);
    return () => window.removeEventListener("hashchange", onChange);
  }, []);

  return route;
}

/** Container width, so charts size to the viewport instead of guessing. */
export function useWidth(fallback = 720) {
  const ref = useRef(null);
  const [width, setWidth] = useState(fallback);

  useEffect(() => {
    const node = ref.current;
    if (!node) return;
    const ro = new ResizeObserver(([entry]) => {
      const w = entry.contentRect.width;
      if (w > 0) setWidth(w);
    });
    ro.observe(node);
    return () => ro.disconnect();
  }, []);

  return [ref, width];
}

export const fmt = (n) =>
  n === null || n === undefined ? "—" : Math.round(n).toLocaleString("en-US");

/** A 0-1 rate as a whole-number percentage. */
export const pct = (n) => (n === null || n === undefined ? "—" : `${Math.round(n * 100)}%`);

/** The side every first-person number is phrased for. `hero_team` is null when
 *  no focal player was recorded, in which case the UI falls back to Blue and
 *  says so rather than implying a "you" the data cannot support. */
export const heroTeam = (match) => match?.hero_team || "Blue";

export const otherTeam = (team) => (team === "Red" ? "Blue" : "Red");
