"""Store -> static JSON bundles for the dashboard.

The frontend has no backend and no credentials: it fetches these files and
nothing else. That is the whole point of pre-generating them -- a static host
cannot leak an API key it was never given.

Two shapes:
  index.json          the match list, plus the provenance banner text
  match/<id>.json     one match: meta, players, round timeline, economy series,
                      debrief, and the Phase 3 decision trace verbatim

Bundles carry no timestamps and sort every collection, so re-exporting an
unchanged store produces byte-identical files. Same property the trace has, for
the same reason: a diff should only appear when something actually changed.

Usage:
    python -m src.export.bundle                      # -> web/public/data
    python -m src.export.bundle --matches 12
    python -m src.export.bundle --llm                # phrase debriefs via API
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path
from typing import Any

from src.agents.debrief import debrief
from src.features.constants import BUY_NAMES
from src.riot.resolve import ContentResolver, default_resolver
from src.storage.init import init as init_db

BUNDLE_VERSION = 1
DEFAULT_OUT = Path("web/public/data")

# Shown on every view. The honesty is the pitch, so it lives in the bundle
# rather than in frontend copy -- it ships with the data it describes.
PROVENANCE_NOTE = (
    "Simulated data conforming to the val-match-v1 schema "
    "— production key application pending"
)
PROVENANCE_DETAIL = (
    "val-match-v1 requires a Riot production key. Matches here are generated by "
    "an in-repo simulator that emits payloads in the documented val-match-v1 "
    "shape, grounded in real agent and map UUIDs fetched live from val-content-v1. "
    "Nothing is scraped and no unofficial API is used. Every module downstream of "
    "the match adapter is source-agnostic, so live data swaps in with no code change."
)

# Per-team, per-round signals the timeline renders. Feature name -> bundle key.
_TEAM_ROUND_FEATURES = {
    "spend": "spend",
    "bank": "bank",
    "spend_trend3": "spend_trend3",
    "loss_streak": "loss_streak",
    "broken_buy": "broken_buy",
}


def _feature_map(conn: sqlite3.Connection, match_id: str) -> dict[tuple[str, int], float]:
    rows = conn.execute(
        "SELECT round_num, name, value FROM features WHERE match_id = ?", (match_id,)
    ).fetchall()
    return {(r["name"], r["round_num"]): r["value"] for r in rows}


def _match_meta(conn: sqlite3.Connection, match_id: str,
                resolver: ContentResolver) -> dict[str, Any]:
    m = conn.execute(
        """SELECT match_id, map_id, game_length_ms, game_start_ms, queue_id,
                  season_id, source
           FROM matches WHERE match_id = ?""",
        (match_id,),
    ).fetchone()
    if m is None:
        raise SystemExit(f"match {match_id!r} not in the store -- ingest it first")

    wins = dict(conn.execute(
        """SELECT winning_team, COUNT(*) FROM rounds
           WHERE match_id = ? AND winning_team IS NOT NULL
           GROUP BY winning_team""",
        (match_id,),
    ).fetchall())
    score = {"Blue": wins.get("Blue", 0), "Red": wins.get("Red", 0)}
    winner = max(score, key=lambda t: score[t]) if score["Blue"] != score["Red"] else None

    return {
        "match_id": m["match_id"],
        "map_id": m["map_id"],
        "map_name": resolver.map_name(m["map_id"]),
        "queue_id": m["queue_id"],
        "game_length_ms": m["game_length_ms"],
        "source": m["source"],
        "rounds": sum(score.values()),
        "score": score,
        "winner": winner,
    }


def _players(conn: sqlite3.Connection, match_id: str,
             resolver: ContentResolver) -> list[dict[str, Any]]:
    rows = conn.execute(
        """SELECT puuid, team_id, character_id, competitive_tier,
                  score, kills, deaths, assists
           FROM match_players WHERE match_id = ?
           ORDER BY team_id, score DESC, puuid""",
        (match_id,),
    ).fetchall()
    return [
        {
            "puuid": r["puuid"],
            "team_id": r["team_id"],
            "character_id": r["character_id"],
            "agent_name": resolver.agent_name(r["character_id"]),
            "competitive_tier": r["competitive_tier"],
            "score": r["score"],
            "kills": r["kills"],
            "deaths": r["deaths"],
            "assists": r["assists"],
        }
        for r in rows
    ]


def _rounds(conn: sqlite3.Connection, match_id: str,
            features: dict[tuple[str, int], float]) -> list[dict[str, Any]]:
    """The round timeline: outcome plus the economy features drawn beneath it."""
    rows = conn.execute(
        """SELECT round_num, winning_team, round_result, plant_site, plant_ms, defuse_ms
           FROM rounds WHERE match_id = ? ORDER BY round_num""",
        (match_id,),
    ).fetchall()

    pivotal = features.get(("pivotal_round", -1))

    out = []
    for r in rows:
        rn = r["round_num"]
        economy: dict[str, dict[str, Any]] = {}
        for team in ("Blue", "Red"):
            buy_code = features.get((f"buy_type:{team}", rn))
            team_econ: dict[str, Any] = {
                "buy_type": BUY_NAMES.get(buy_code) if buy_code is not None else None,
            }
            for feat, key in _TEAM_ROUND_FEATURES.items():
                team_econ[key] = features.get((f"{feat}:{team}", rn))
            economy[team] = team_econ

        out.append({
            "round_num": rn,
            "winning_team": r["winning_team"],
            "round_result": r["round_result"],
            "plant_site": r["plant_site"],
            "plant_ms": r["plant_ms"],
            "defuse_ms": r["defuse_ms"],
            "spend_diff": features.get(("spend_diff", rn)),
            "economy": economy,
            "pivotal": pivotal is not None and int(pivotal) == rn,
        })
    return out


def _match_features(features: dict[tuple[str, int], float]) -> dict[str, float]:
    """Match-scoped feature rows (round sentinel -1), for the summary strip."""
    return {name: value for (name, rn), value in features.items() if rn == -1}


def build_match_bundle(conn: sqlite3.Connection, match_id: str,
                       use_llm: bool = False,
                       resolver: ContentResolver | None = None) -> dict[str, Any]:
    resolver = resolver or default_resolver()
    report, conclusions, trace = debrief(conn, match_id, use_llm=use_llm)
    features = _feature_map(conn, match_id)

    return {
        "bundle_version": BUNDLE_VERSION,
        "provenance": {"note": PROVENANCE_NOTE, "detail": PROVENANCE_DETAIL},
        "match": _match_meta(conn, match_id, resolver),
        "players": _players(conn, match_id, resolver),
        "rounds": _rounds(conn, match_id, features),
        "match_features": _match_features(features),
        "debrief": {
            "text": report.text,
            "used_llm": report.used_llm,
            "error": report.error,
            "rejected_numerals": report.rejected_numerals,
        },
        # Verbatim Phase 3 trace. The UI expands claims straight out of this;
        # reshaping it here would put a second definition of "evidence" in play.
        "trace": trace,
        "excluded": [
            {"rule_id": c.rule_id, "reason": c.unverified_reason}
            for c in conclusions if c.verified is not True
        ],
    }


def build_index(bundles: list[dict[str, Any]]) -> dict[str, Any]:
    matches = []
    for b in bundles:
        summary = b["trace"]["summary"]
        matches.append({
            **b["match"],
            "verified_claims": summary["verified"],
            "unverified_claims": summary["unverified"],
            "source_rows_cited": summary["source_rows_cited"],
            "severities": _severity_counts(b["trace"]["conclusions"]),
        })

    sources = sorted({m["source"] for m in matches})
    return {
        "bundle_version": BUNDLE_VERSION,
        "provenance": {
            "note": PROVENANCE_NOTE,
            "detail": PROVENANCE_DETAIL,
            "sources": sources,
        },
        "match_count": len(matches),
        "matches": sorted(matches, key=lambda m: m["match_id"]),
    }


def _severity_counts(conclusions: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for c in conclusions:
        if c["verified"] is True:
            counts[c["severity"]] = counts.get(c["severity"], 0) + 1
    return counts


def dumps(obj: Any) -> str:
    """Stable serialization: sorted keys, fixed indent, trailing newline."""
    return json.dumps(obj, indent=2, sort_keys=True) + "\n"


def export(conn: sqlite3.Connection, out_dir: Path, limit: int | None = None,
           use_llm: bool = False) -> dict[str, Any]:
    match_ids = [r["match_id"] for r in conn.execute(
        "SELECT match_id FROM matches ORDER BY match_id")]
    if not match_ids:
        raise SystemExit("store is empty -- run `python -m src.ingest.pipeline --source sim`")
    if limit:
        match_ids = match_ids[:limit]

    resolver = default_resolver()
    match_dir = out_dir / "match"
    match_dir.mkdir(parents=True, exist_ok=True)

    bundles = []
    for mid in match_ids:
        bundle = build_match_bundle(conn, mid, use_llm=use_llm, resolver=resolver)
        (match_dir / f"{mid}.json").write_text(dumps(bundle), encoding="utf-8")
        bundles.append(bundle)

    index = build_index(bundles)
    (out_dir / "index.json").write_text(dumps(index), encoding="utf-8")

    return {
        "matches": len(bundles),
        "verified_claims": sum(m["verified_claims"] for m in index["matches"]),
        "out": str(out_dir),
    }


if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()

    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="bundle output directory")
    ap.add_argument("--matches", type=int, default=None,
                    help="export only the first N matches")
    ap.add_argument("--llm", action="store_true",
                    help="phrase debriefs via the API (default: template text, no key needed)")
    args = ap.parse_args()

    result = export(init_db(), Path(args.out), limit=args.matches, use_llm=args.llm)
    print(f"exported {result['matches']} matches "
          f"({result['verified_claims']} verified claims) -> {result['out']}")
